### PR TITLE
F11 login frame

### PR DESCRIPTION
**Pull request by yangysu**
This is the GUI for the Login Frame. 

- added program title "Study Buddy Finder"
- added combobox for user to select user type
- added textfield for user to enter USER ID
- added passwordfield for user to enter Password 
- added two buttons [Login, Register] for user to Login to current account or Create a new account

### CODE REVIEW

**Review by lob43 — DISMISSED** [review]
You can remove the user type Combobox since we already know the user type when we are registering the user.

**Review by gheneral — COMMENTED** [review]
It would be a good idea to add a new register frame for the user to Register a new account, so that it creates less conflict with the current frame.

**Review by gheneral — APPROVED** [review]
But we can merge it to main and update small details as we go to milestone 5

**Comment by Harvir21** [comment]
We can remove the Email textfield since we are adding a new register frame and we are recording the user's Email in the register frame.

**Pull request merged**
